### PR TITLE
fix: under-counting metrics for enum is_enabled()

### PR DESCRIPTION
**Pull request by rbtcollins**
- **fix: under-counting metrics for enum is_enabled()**
- **Release**

### CODE REVIEW

**Review by chriswk — APPROVED** [review]
LGTM - thank you!

**Comment by rbtcollins** [comment]
I figured out - this was a regression in 26eaac3af39f9ced77743e3745279b0ed48bbade (@thomasheartman )

**Comment by thomasheartman** [comment]
Oh, wow. Good catch! Might be worth adding some tests for it so that we avoid it happening again?

**Comment by rbtcollins** [comment]
I think the str case is already tested, this is oversight indeed; we should add some tests; it may be a bit before I have time to do that myself

**Pull request merged**
